#=========================================
#  MiniGame Player Queue plugin 
#  Version:    ${version} 
#  Build time: - - -
#=========================================

debug: false

//check-updates: true
//send-metrics: true


